[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "public_transportation"
dynamic = ["version"]
description = "Tools for public transportation modeling and analysis"
authors = [{name = "Michel Bierlaire", email = "michel.bierlaire@epfl.ch"}]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.12,<3.15"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
]

dependencies = [
    "numpy",
    "pandas",
    "numpyro==0.21.0",
    "jax==0.11.0",
    "jaxlib==0.11.0",
    "matplotlib",
    "scipy",
    "threadpoolctl",
    "pyyaml",
    "biogeme-optimization>=0.0.13,<0.1",
]


[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
    "mypy",
    "tox"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "public_transportation.version.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["."]
