[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "public_transportation"
dynamic = ["version"]
description = "Tools for public transportation modeling and analysis"
authors = [{name = "Michel Bierlaire"}]
readme = "README.md"
requires-python = ">=3.14,<3.15"

dependencies = [
    "numpy",
    "pandas",
    "numpyro==0.21.0",
    "jax==0.11.0",
    "jaxlib==0.11.0",
    "matplotlib",
    "scipy",
    "threadpoolctl",
]


[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
    "mypy"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "public_transportation.version.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["."]
