[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "public_transportation"
dynamic = ["version"]
description = "Tools for public transportation modeling and analysis"
authors = [{name = "Michel Bierlaire"}]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pandas",
    "jax",
    "jaxlib",
    "numpyro",
    "matplotlib",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
    "mypy"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "public_transportation.version.__version__"}

[tool.setuptools.packages.find]
where = ["src"]