"""Example 02: two OD pairs, two partially-overlapping lines, time-varying demand.

This script expects the following files next to it in ./data:
- metadata.json
- stops.csv
- lines.csv
- trips.csv
- stop_times.csv
- time_bins.csv
- demand.csv

Workflow:
1) load the Scenario from the data folder,
2) run the assignment (with per-group link flows),
3) generate one HTML report per OD-group (so costs/flows match exactly what the model uses),
4) print a compact summary of totals by link type.

Constraints:
- No new helper functions are defined in this script.
- Use only the domain/assignment API provided by the package.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import jax.numpy as jnp

from public_transportation.domain import TimeOfDay
from public_transportation.domain.scenario import Scenario
from public_transportation.assignment.config import AssignmentConfig
from public_transportation.assignment.assign import assign
from public_transportation.assignment.assign import prepare_assignment
from public_transportation.measurement.schema import (
    MeasurementRecord,
    MeasurementTable,
    MeasurementType,
)
from public_transportation.viz.time_expanded_report import write_time_expanded_report_from_assignment

# Measurement IO (generated by this example)
from public_transportation.measurement.io import write_measurements_csv

DATA = Path(__file__).resolve().parent / "data"

# 1) Load scenario from data
scenario = Scenario.from_folder(DATA)

# Optional: validate and print any issues
rep = scenario.validate()
if rep.issues:
    print("Scenario validation issues:")
    for it in rep.issues:
        print(f"- [{it.severity.name}] {it.code}: {it.message} ({it.location})")

# 2) Assign demand
if scenario.demand is None or not scenario.demand.records:
    raise RuntimeError("No demand records found.")

od_values = jnp.asarray([float(r.flow) for r in scenario.demand.records], dtype=jnp.float32)
config = AssignmentConfig()

artifacts = prepare_assignment(scenario=scenario, config=config)
res = assign(
    od_values=od_values,
    artifacts=artifacts,
    theta=None,
    # No per-group flows here: grouping is an internal feature of the assignment module.
    return_group_link_flows=False,
)

print("Example 02 — overlapping lines, time-varying demand")
print(f"OD records: {len(scenario.demand.records)}")
print(f"Total demand: {float(np.asarray(od_values).sum()):.6g}")
print(f"Theta used: {res.theta:.6g}")

# 3) Generate reporting (single report; no OD grouping logic in this script)
# The report must not compute link costs: we expect them to be present in the assignment result.
# Accessing these attributes directly is intentional: missing attributes should raise immediately.
_ = res.link_flow
_ = res.link_cost

report_dir = DATA
report_dir.mkdir(parents=True, exist_ok=True)

report_path = report_dir / "time_expanded_report.html"

write_time_expanded_report_from_assignment(
    scenario=scenario,
    assignment=res,
    config=config,
    output_path=report_path,
    title="Example 02 — time-expanded graph report",
    svg_scale_x=1.8,
    svg_scale_y=2.4,
)

print(f"Report written to: {report_path}")

# 4) Generate synthetic measurements (boarding/alighting) from the assignment result
# For testing purposes, we interpret:
#   - boarding  := flow on ACCESS links (centroid_in -> event_dep)
#   - alighting := flow on EGRESS links (event_arr -> centroid_out)
# Measurements are timestamped using the timetable event time (node_time_s of the event node).

graph = artifacts.graph
link_flow = np.asarray(res.link_flow)
link_type = np.asarray(graph.link_type)
tail = np.asarray(graph.tail)
head = np.asarray(graph.head)
node_time_s = np.asarray(graph.node_time_s)
node_stop_index = np.asarray(graph.node_stop_index)
node_trip_index = np.asarray(graph.node_trip_index)

stop_ids = list(graph.node_stop_id)
trip_ids = list(graph.trip_id)


def _hms_from_seconds(sec: int) -> str:
    sec = int(sec)
    if sec < 0:
        sec = 0
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    return f"{h:02d}:{m:02d}:{s:02d}"


def _stop_id_from_node(n: int) -> str:
    si = int(node_stop_index[n])
    return str(stop_ids[si])


def _trip_id_from_node(n: int) -> str | None:
    ti = int(node_trip_index[n])
    if ti < 0:
        return None
    return str(trip_ids[ti])



# Aggregate measurements by (type, stop_id, trip_id, time)
agg: dict[tuple[str, str, str | None, str], float] = {}

# Keep track of which time-expanded links contribute to each aggregated measurement key.
# Key is the same as in `agg`: (measurement_type, stop_id, trip_id, time_hms)
# Value is a list of dicts with link id and contribution value.
contrib: dict[tuple[str, str, str | None, str], list[dict[str, float | int]]] = {}

# Boarding from ACCESS links: use the DEPARTURE event node at the head
access_idx = np.where(link_type == 2)[0]  # LINK_TYPE_ACCESS
for lid in access_idx:
    v = float(link_flow[lid])
    if v == 0.0:
        continue
    n = int(head[lid])
    key = (
        "boarding",
        _stop_id_from_node(n),
        _trip_id_from_node(n),
        _hms_from_seconds(int(node_time_s[n])),
    )
    agg[key] = agg.get(key, 0.0) + v
    contrib.setdefault(key, []).append({"link_id": int(lid), "value": float(v)})

# Alighting from EGRESS links: use the ARRIVAL event node at the tail

egress_idx = np.where(link_type == 3)[0]  # LINK_TYPE_EGRESS
for lid in egress_idx:
    v = float(link_flow[lid])
    if v == 0.0:
        continue
    n = int(tail[lid])
    key = (
        "alighting",
        _stop_id_from_node(n),
        _trip_id_from_node(n),
        _hms_from_seconds(int(node_time_s[n])),
    )
    agg[key] = agg.get(key, 0.0) + v
    contrib.setdefault(key, []).append({"link_id": int(lid), "value": float(v)})

# Build MeasurementRecord objects (schema.py) and write using io.py.
records: list[MeasurementRecord] = []

for (mtype, stop_id, trip_id, time_hms), value in sorted(agg.items()):
    # Schema requires at least one of (trip_id, line_id). For this synthetic data,
    # we only emit trip-specific observations.
    if trip_id is None:
        continue

    # Convert HH:MM:SS -> TimeOfDay
    hh, mm, ss = (int(x) for x in time_hms.split(":"))
    t = TimeOfDay(seconds_from_midnight=hh * 3600 + mm * 60 + ss)

    records.append(
        MeasurementRecord(
            method_id="synthetic_from_assignment",
            measurement_type=MeasurementType(mtype),  # "boarding" / "alighting"
            stop_id=stop_id,
            time=t,
            value=float(value),
            trip_id=trip_id,
            line_id=None,
        )
    )

table = MeasurementTable.from_records(records)

meas_path = report_dir / "measurements_boarding_alighting.csv"
write_measurements_csv(table, meas_path)
print(f"Synthetic measurements written to: {meas_path}")

# 5) Generate a mapping report: each synthetic measurement -> contributing time-expanded links
# The link ids referenced here are the same link indices used in the time_expanded_report.html.
map_path = report_dir / "synthetic_measurement_link_mapping.md"

# Precompute some link/node metadata for readable reporting
link_tail = tail
link_head = head

def _node_hms(n: int) -> str:
    return _hms_from_seconds(int(node_time_s[n]))

with open(map_path, "w", encoding="utf-8") as f:
    f.write("# Synthetic measurement → contributing links\n\n")
    f.write("This report explains how each synthetic boarding/alighting count was generated from the assigned link flows.\n")
    f.write("Link indices refer to the time-expanded network links shown in `time_expanded_report.html`.\n\n")

    for (mtype, stop_id, trip_id, time_hms), value in sorted(agg.items()):
        # Keep the same filtering rule as the CSV export
        if trip_id is None:
            continue

        f.write(f"## {mtype} — stop={stop_id}, trip={trip_id}, time={time_hms}\n\n")
        f.write(f"Aggregated value: **{float(value):.6g}**\n\n")

        parts = contrib.get((mtype, stop_id, trip_id, time_hms), [])
        if not parts:
            f.write("No contributing links found (unexpected).\n\n")
            continue

        f.write("| link_id | contribution | link_type | tail_node | tail_stop | tail_time | head_node | head_stop | head_time |\n")
        f.write("|---:|---:|---:|---:|:---|:---|---:|:---|:---|\n")

        # Sort by link id for stability
        parts_sorted = sorted(parts, key=lambda d: int(d["link_id"]))
        for p in parts_sorted:
            lid = int(p["link_id"])
            v = float(p["value"])
            t = int(link_tail[lid])
            h = int(link_head[lid])
            lt = int(link_type[lid])
            f.write(
                "| "
                f"{lid} | {v:.6g} | {lt} | {t} | {_stop_id_from_node(t)} | {_node_hms(t)} | "
                f"{h} | {_stop_id_from_node(h)} | {_node_hms(h)} |\n"
            )

        f.write("\n")

print(f"Synthetic measurement mapping report written to: {map_path}")
