"""
Pre-processing for simple_example_01.

This script reads the stable reference data from ../data and writes all generated
files to ./results.

Inputs:
    ../data/metadata.json
    ../data/stops.csv
    ../data/lines.csv
    ../data/trips.csv
    ../data/stop_times.csv
    ../data/time_bins.csv
    ../data/true_demand.csv
    ../data/prior_demand.csv

Outputs:
    results/demand.csv
    results/measurements_boarding_alighting.csv
    results/time_expanded_report_true.html
    results/synthetic_measurement_link_mapping.json
    results/true_assignment.npz
"""

from __future__ import annotations

import json
import shutil
import tempfile
from pathlib import Path

import jax.numpy as jnp
import numpy as np

from public_transportation.assignment.assign import assign, prepare_assignment
from public_transportation.assignment.config import AssignmentConfig
from public_transportation.assignment.graph_sentinels import (
    LINK_TYPE_ACCESS,
    LINK_TYPE_EGRESS,
)
from public_transportation.domain import TimeOfDay
from public_transportation.domain.scenario import Scenario
from public_transportation.measurement.io import write_measurements_csv
from public_transportation.measurement.schema import (
    MeasurementRecord,
    MeasurementTable,
    MeasurementType,
)
from public_transportation.viz.time_expanded_report import (
    write_time_expanded_report_from_assignment,
)

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
RESULTS = Path(__file__).resolve().parent / "results"

NETWORK_FILES = [
    "metadata.json",
    "stops.csv",
    "lines.csv",
    "trips.csv",
    "stop_times.csv",
    "time_bins.csv",
]

MEASUREMENT_FLOW_TOL = 1.0e-8

def _copy_required_file(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(f"Missing required input file: {src}")
    shutil.copy2(src, dst)


def _prepare_scenario_folder(*, demand_file: Path) -> tempfile.TemporaryDirectory[str]:
    """Create a temporary Scenario folder with the selected demand file as demand.csv."""
    tmp = tempfile.TemporaryDirectory()
    tmp_path = Path(tmp.name)

    for filename in NETWORK_FILES:
        _copy_required_file(DATA / filename, tmp_path / filename)

    _copy_required_file(demand_file, tmp_path / "demand.csv")
    return tmp


def _hms_from_seconds(seconds: int) -> str:
    seconds = max(int(seconds), 0)
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:02d}"


def main() -> None:
    RESULTS.mkdir(parents=True, exist_ok=True)

    true_demand_path = DATA / "true_demand.csv"
    prior_demand_path = DATA / "prior_demand.csv"

    if not true_demand_path.exists():
        raise FileNotFoundError(f"Missing true demand file: {true_demand_path}")
    if not prior_demand_path.exists():
        raise FileNotFoundError(f"Missing prior demand file: {prior_demand_path}")

    # The estimation scripts expect a demand.csv file generated by preprocessing.
    # In this example, it is the prior demand.
    generated_demand_path = RESULTS / "demand.csv"
    shutil.copy2(prior_demand_path, generated_demand_path)

    # Build a temporary scenario using the true demand. This avoids writing a
    # generated demand.csv into ../data.
    with _prepare_scenario_folder(demand_file=true_demand_path) as tmp_dir:
        scenario = Scenario.from_folder(Path(tmp_dir))

        report = scenario.validate()
        if report.issues:
            print("Scenario validation issues:")
            for issue in report.issues:
                print(
                    f"- [{issue.severity.name}] {issue.code}: "
                    f"{issue.message} ({issue.location})"
                )

        if scenario.demand is None or not scenario.demand.records:
            raise RuntimeError("No true demand records found.")

        od_values = jnp.asarray(
            [float(record.flow) for record in scenario.demand.records],
            dtype=jnp.float32,
        )

        config = AssignmentConfig()
        artifacts = prepare_assignment(scenario=scenario, config=config)

        assignment = assign(
            od_values=od_values,
            artifacts=artifacts,
            theta=None,
            return_group_link_flows=False,
        )

        print("Pre-processing: synthetic data generation")
        print(f"OD records: {len(scenario.demand.records)}")
        print(f"Total true demand: {float(np.asarray(od_values).sum()):.6g}")
        print(f"Theta used for synthetic assignment: {assignment.theta:.6g}")

        report_path = RESULTS / "time_expanded_report_true.html"
        write_time_expanded_report_from_assignment(
            scenario=scenario,
            assignment=assignment,
            config=config,
            output_path=report_path,
            title="Example 02 — true-demand time-expanded graph report",
            svg_scale_x=1.8,
            svg_scale_y=2.4,
        )

        graph = artifacts.graph
        link_flow = np.asarray(assignment.link_flow)
        link_cost = np.asarray(assignment.link_cost)
        link_type = np.asarray(graph.link_type)
        tail = np.asarray(graph.tail)
        head = np.asarray(graph.head)
        node_time_s = np.asarray(graph.node_time_s)
        node_stop_index = np.asarray(graph.node_stop_index)
        node_trip_index = np.asarray(graph.node_trip_index)

        stop_ids = list(graph.node_stop_id)
        trip_ids = list(graph.trip_id)

        def stop_id_from_node(node: int) -> str:
            stop_index = int(node_stop_index[node])
            return str(stop_ids[stop_index])

        def trip_id_from_node(node: int) -> str | None:
            trip_index = int(node_trip_index[node])
            if trip_index < 0:
                return None
            return str(trip_ids[trip_index])

        def node_hms(node: int) -> str:
            return _hms_from_seconds(int(node_time_s[node]))

        # Synthetic boarding/alighting measurements.
        agg: dict[tuple[str, str, str | None, str], float] = {}
        contrib: dict[tuple[str, str, str | None, str], list[dict[str, float | int]]] = {}

        access_link_ids = np.where(link_type == LINK_TYPE_ACCESS)[0]
        for link_id in access_link_ids:
            value = float(link_flow[link_id])
            if abs(value) <= MEASUREMENT_FLOW_TOL:
                continue

            node = int(head[link_id])
            key = (
                "boarding",
                stop_id_from_node(node),
                trip_id_from_node(node),
                node_hms(node),
            )
            agg[key] = agg.get(key, 0.0) + value
            contrib.setdefault(key, []).append(
                {"link_id": int(link_id), "value": value}
            )

        egress_link_ids = np.where(link_type == LINK_TYPE_EGRESS)[0]
        for link_id in egress_link_ids:
            value = float(link_flow[link_id])
            if abs(value) <= MEASUREMENT_FLOW_TOL:
                continue

            node = int(tail[link_id])
            key = (
                "alighting",
                stop_id_from_node(node),
                trip_id_from_node(node),
                node_hms(node),
            )
            agg[key] = agg.get(key, 0.0) + value
            contrib.setdefault(key, []).append(
                {"link_id": int(link_id), "value": value}
            )

        records: list[MeasurementRecord] = []

        for (measurement_type, stop_id, trip_id, time_hms), value in sorted(agg.items()):
            if trip_id is None:
                continue

            hh, mm, ss = (int(part) for part in time_hms.split(":"))
            time = TimeOfDay(seconds_from_midnight=hh * 3600 + mm * 60 + ss)

            records.append(
                MeasurementRecord(
                    method_id="synthetic_from_true_assignment",
                    measurement_type=MeasurementType(measurement_type),
                    stop_id=stop_id,
                    time=time,
                    value=float(value),
                    trip_id=trip_id,
                    line_id=None,
                )
            )

        measurement_table = MeasurementTable.from_records(records)
        measurements_path = RESULTS / "measurements_boarding_alighting.csv"
        write_measurements_csv(measurement_table, measurements_path)

        mapping_path = RESULTS / "synthetic_measurement_link_mapping.json"
        mapping_records = []
        for (measurement_type, stop_id, trip_id, time_hms), value in sorted(agg.items()):
            if trip_id is None:
                continue
            parts = sorted(
                contrib.get((measurement_type, stop_id, trip_id, time_hms), []),
                key=lambda item: int(item["link_id"]),
            )
            links = []
            for part in parts:
                link_id = int(part["link_id"])
                tail_node = int(tail[link_id])
                head_node = int(head[link_id])
                links.append(
                    {
                        "link_id": link_id,
                        "contribution": float(part["value"]),
                        "link_type": int(link_type[link_id]),
                        "tail_node": tail_node,
                        "tail_stop": stop_id_from_node(tail_node),
                        "tail_time": node_hms(tail_node),
                        "head_node": head_node,
                        "head_stop": stop_id_from_node(head_node),
                        "head_time": node_hms(head_node),
                    }
                )
            mapping_records.append(
                {
                    "measurement_type": measurement_type,
                    "stop_id": stop_id,
                    "trip_id": trip_id,
                    "time": time_hms,
                    "value": float(value),
                    "contributing_links": links,
                }
            )
        mapping_path.write_text(
            json.dumps(
                {
                    "schema_version": 1,
                    "description": (
                        "Synthetic boarding/alighting measurements and their "
                        "contributing assigned links."
                    ),
                    "assignment_report": report_path.name,
                    "measurements": mapping_records,
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )

        true_assignment_path = RESULTS / "true_assignment.npz"
        np.savez_compressed(
            true_assignment_path,
            theta=float(assignment.theta),
            od_values=np.asarray(od_values, dtype=float),
            link_flow=link_flow,
            link_cost=link_cost,
        )

        summary_path = RESULTS / "preprocessing_summary.json"
        summary = {
            "source_data_dir": str(DATA),
            "results_dir": str(RESULTS),
            "true_demand_file": str(true_demand_path),
            "prior_demand_file": str(prior_demand_path),
            "generated_demand_file": str(generated_demand_path),
            "measurements_file": str(measurements_path),
            "time_expanded_report": str(report_path),
            "measurement_mapping_json": str(mapping_path),
            "true_assignment_file": str(true_assignment_path),
            "num_od_records": len(scenario.demand.records),
            "total_true_demand": float(np.asarray(od_values).sum()),
            "theta": float(assignment.theta),
            "num_measurements": len(records),
        }
        summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print()
    print("Pre-processing complete.")
    print()
    print("Generated files:")
    print(f"  {generated_demand_path}")
    print(f"  {measurements_path}")
    print(f"  {report_path}")
    print(f"  {mapping_path}")
    print(f"  {true_assignment_path}")
    print(f"  {summary_path}")
    print()
    print("Next step:")
    print("  cd ../estimation")
    print("  python run_both.py")
    print()
    print("The estimation scripts should read:")
    print(f"  stable scenario files from: {DATA}")
    print(f"  generated estimation inputs from: {RESULTS}")


if __name__ == "__main__":
    main()
