"""Pre-estimation tools for deriving reproducible model inputs."""

from .structural_zeros import (
    FixedDemandReconciliationResult,
    ODPathMetrics,
    ODPathMetricRecord,
    ODTimeKey,
    PRIMARY_REASON_PRECEDENCE,
    StructuralZeroAnalysisResult,
    StructuralZeroConfig,
    StructuralZeroConflictError,
    StructuralZeroReason,
    StructuralZeroRecord,
    StructuralZeroOutputPaths,
    StructuralZeroExecutionResult,
    StructuralZeroTopology,
    analyze_structural_zeros,
    build_structural_zero_topology,
    compute_od_path_metrics,
    classify_structural_zeros,
    fingerprint_scenario,
    load_structural_zero_config,
    load_and_reconcile_fixed_demand,
    reconcile_fixed_demand,
    run_structural_zero_preprocessing,
    scenario_fingerprint_payload_json,
    write_structural_zero_outputs,
)
from .structural_zeros.errors import StructuralZeroConfigError

__all__ = [
    "FixedDemandReconciliationResult",
    "ODPathMetrics",
    "ODPathMetricRecord",
    "ODTimeKey",
    "PRIMARY_REASON_PRECEDENCE",
    "StructuralZeroAnalysisResult",
    "StructuralZeroConfig",
    "StructuralZeroConfigError",
    "StructuralZeroConflictError",
    "StructuralZeroReason",
    "StructuralZeroRecord",
    "StructuralZeroOutputPaths",
    "StructuralZeroExecutionResult",
    "StructuralZeroTopology",
    "analyze_structural_zeros",
    "build_structural_zero_topology",
    "compute_od_path_metrics",
    "classify_structural_zeros",
    "fingerprint_scenario",
    "load_structural_zero_config",
    "load_and_reconcile_fixed_demand",
    "reconcile_fixed_demand",
    "run_structural_zero_preprocessing",
    "scenario_fingerprint_payload_json",
    "write_structural_zero_outputs",
]
